root = "." # the root directory
temp_dir = "./tmp" # the temporary directory

[build]
bin = "main" # the binary name
cmd = "go build -o {{.Output}} {{.Input}}" # the command to build the project
include = ["**/*.go"] # the files to include
exclude_dir = ["tmp", "client"] # the directories to exclude

